version: '3.8'

x-postgres-common:
  &postgres-common
  image: postgres:14-alpine
  user: postgres
  restart: always
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U user --dbname=postgres"]
    interval: 10s
    timeout: 5s
    retries: 5

services:
  postgres_primary:
    <<: *postgres-common
    container_name: postgres_primary
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      command: |
        postgres -c 'wal_level=replica' \
               -c 'hot_standby=on' \
               -c 'max_wal_senders=10' \
               -c 'listen_addresses=*' \
               -c 'max_replication_slots=10' \
               -c 'hot_standby_feedback=on'
    volumes:
      - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./01_init_usuarios.sql:/docker-entrypoint-initdb.d/01_init_usuarios.sql
    networks:
      - mynetwork

  postgres_replica:
    <<: *postgres-common
    container_name: postgres_replica
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: replicator_password

    depends_on:
      - postgres_primary
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge